apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./base-sales.yaml
images:
- name: sales-api-image
  newName: sales-api-amd64
  newTag: "1.0"
- name: openzipkin
  newName: openzipkin/zipkin
  newTag: "2.23"
